### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by Paul-dH** [elkarbackup/elkarbackup-docker#18]
Hi,

I get a error during the installation inside the container (development version):
```
  [Doctrine\DBAL\Exception\ConnectionException]                                                                                   
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'172.19.0.3' (using password: YES)  
                                                         
  [Doctrine\DBAL\Driver\PDOException]                                                             
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'172.19.0.3' (using password: YES)  
                                                                        
  [PDOException]                                                                                  
  SQLSTATE[HY000] [1045] Access denied for user 'elkarbackup'@'172.19.0.3' (using password: YES)  
```

I'm using the below docker-compose file:
```
version: '2'

services:

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    stop_grace_period: 60s

  elkarbackup:
    image: elkarbackup/elkarbackup:dev
    container_name: elkarbackup
    ports:
      - 8080:80
      - 8443:443
    links:
      - db
    depends_on:
      - db
    environment:
      EB_DB_PASSWORD: rootpassword
      EB_PATH: /usr/local/elkarbackup
      EB_VERSION: https://github.com/xezpeleta/elkarbackup.git
    volumes:
      - /data/elkarbackup:/usr/local/elkarbackup
    stop_grace_period: 60s
```
I've also tried the default :latest image but no luck either:

```
ACLs not supported. Remount with ACL and reconfigure with 'dpkg --configure --pending'
dpkg: error processing package elkarbackup (--configure):
subprocess installed post-installation script returned error exit status 1
```
This look exacly the same as: [Issue 12](https://github.com/elkarbackup/elkarbackup-docker/issues/12), I've tried to enable acl trough fstab, but no luck.

I'm on Ubuntu 17.04 server

Docker:
```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:18:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:17:03 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
