### ISSUE TITLE
Errors on Docker-compose up : missing config files

### ISSUE THREAD

**Issue by shyamjos** [elkarbackup/elkarbackup-docker#22]
docker-file.yml
```
version: '2'

services:

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql

  elkarbackup:
    image: elkarbackup/elkarbackup
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    volumes:
        - ./elkarbackup/config:/etc/elkarbackup
        - ./elkarbackup/data:/var/spool/elkarbackup
    environment:
      EB_DB_PASSWORD: example

```

I am getting below error when bringing up the docker containers 

```
elkarbackup_1  | Attempting to create DB elkarbackup and user elkarbackup in db
elkarbackup_1  | Create database
elkarbackup_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
elkarbackup_1  | Create user
elkarbackup_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
elkarbackup_1  | sed: can't read /etc/elkarbackup/config.yml: No such file or directory
elkarbackup_1  | Configure parameters
elkarbackup_1  | sed: can't read /etc/elkarbackup/parameters.yml: No such file or directory
elkarbackup_1  | sed: can't read /etc/elkarbackup/parameters.yml: No such file or directory
elkarbackup_1  | sed: can't read /etc/elkarbackup/parameters.yml: No such file or directory
elkarbackup_1  | sed: can't read /etc/elkarbackup/parameters.yml: No such file or directory
elkarbackup_1  | Delete cache content
elkarbackup_1  | Update DB
elkarbackup_1  | 
elkarbackup_1  |                                                                                 
elkarbackup_1  |   [InvalidArgumentException]                                                    
elkarbackup_1  |   The file "/usr/share/elkarbackup/app/config/config_prod.yml" does not exist.  
elkarbackup_1  |                                                                                 
elkarbackup_1  | 
elkarbackup_1  | Create root user
elkarbackup_1  | 
elkarbackup_1  |                                                                                 
elkarbackup_1  |   [InvalidArgumentException]                                                    
elkarbackup_1  |   The file "/usr/share/elkarbackup/app/config/config_prod.yml" does not exist.  
elkarbackup_1  |                                                                                 
elkarbackup_1  | 
elkarbackup_1  | Clean cache
elkarbackup_1  | 
elkarbackup_1  |                                                                                 
elkarbackup_1  |   [InvalidArgumentException]                                                    
elkarbackup_1  |   The file "/usr/share/elkarbackup/app/config/config_prod.yml" does not exist.  
elkarbackup_1  |                                                                                 
elkarbackup_1  | 
elkarbackup_1  | Dump assets
elkarbackup_1  | 
elkarbackup_1  |                                                                                 
elkarbackup_1  |   [InvalidArgumentException]                                                    
elkarbackup_1  |   The file "/usr/share/elkarbackup/app/config/config_prod.yml" does not exist.  
elkarbackup_1  |                                                                                 
elkarbackup_1  | 
elkarbackup_1  | Invalidate sessions
elkarbackup_1  | Changing file permissions
elkarbackup_1  | chown: cannot access '/etc/elkarbackup/parameters.yml': No such file or directory
elkarbackup_1  | chown: cannot access '/var/spool/elkarbackup/uploads': No such file or directory
elkarbackup_1  | cat: /etc/elkarbackup/parameters.yml: No such file or directory
elkarbackup_1  | mv: cannot remove '/dev/shm': Device or resource busy
elkarbackup_1  | mv: cannot remove '/dev/mqueue': Device or resource busy
elkarbackup_1  | mv: cannot remove '/dev/pts/ptmx': Operation not permitted
elkarbackup_1  | mv: cannot remove '/etc/hosts': Device or resource busy
elkarbackup_1  | mv: cannot remove '/etc/hostname': Device or resource busy
elkarbackup_1  | mv: cannot remove '/etc/resolv.conf': Device or resource busy
elkarbackup_1  | mv: cannot remove '/etc/elkarbackup': Device or resource busy
elkarbackup_1  | mv: error reading '/proc/1/attr/exec': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/prev': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/fscreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/keycreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/sockcreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/current': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/prev': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/exec': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/fscreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/keycreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/selinux/sockcreate': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/smack/current': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/apparmor/prev': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/attr/apparmor/exec': Invalid argument
elkarbackup_1  | mv: error reading '/proc/1/task/1/personality': Operation not permitted
elkarbackup_1  | mv: error reading '/proc/1/task/1/syscall': Operation not permitted
elkarbackup_1  | mv: cannot open '/proc/1/task/1/mem' for reading: Permission denied
elkarbackup_1  | mv: error reading '/proc/1/task/1/clear_refs': Invalid argument
^CGracefully stopping... (press Ctrl+C again to force)
Stopping elakar_elkarbackup_1 ... done
Stopping elakar_db_1      
```

**Comment by xezpeleta** [comment]
Hi @shyamjos 

I'm preparing a new docker image. I'll keep you updated.

Thanks

**Comment by shyamjos** [comment]
Thanks for the update, when can I expect it ?

**Comment by xezpeleta** [comment]
Hi @shyamjos 

Meanwhile, can you try with the following `docker-compose.yml` ?

```yaml
version: '3'

services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql:/var/lib/mysql

  elkarbackup:
    image: elkarbackup/elkarbackup:latest
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./backups:/var/spool/elkarbackup/backups
      - ./upload:/var/spool/elkarbackup/uploads
      - ./logs:/var/log/elkarbackup
    environment:
      EB_DB_HOST: db
      #EB_DB_USER: root
      EB_DB_PASSWORD: example
      #EB_DB_USERPASSWORD: elkarbackup
```
