### ISSUE TITLE
docker-compose.yml incorrect format of volume section

### ISSUE THREAD

**Issue by kovalroma** [elkarbackup/elkarbackup-docker#31]
[Here](https://hub.docker.com/r/elkarbackup/elkarbackup/) is wrong example of docker-compose.yml

Instead of: 
```
version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:1.3.1-apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
      EB_CRON: "enabled"
      volumes:
      - backups:/app/backups
      - uploads:/app/uploads
      - sshkeys:/app/.ssh
    ports:
      - 8000:80

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql

  client:
    image: elkarbackup/client

volumes:
  db:
  backups:
  uploads:
  sshkeys:
```

Should be:

```
version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:1.3.1-apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
      EB_CRON: "enabled"
    volumes:
      - backups:/app/backups
      - uploads:/app/uploads
      - sshkeys:/app/.ssh
    ports:
      - 8000:80

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql

  client:
    image: elkarbackup/client

volumes:
  db:
  backups:
  uploads:
  sshkeys:
```

We need to move ***volumes*** section upper.
