### ISSUE TITLE
Add more information to the docket hub for quick start

### ISSUE THREAD

**Issue by kovalroma** [elkarbackup/elkarbackup-docker#32]
When I first run this docker-compose 
```
version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:1.3.1-apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "your-password-here"
      EB_CRON: "enabled"
    volumes:
      - backups:/app/backups
      - uploads:/app/uploads
      - sshkeys:/app/.ssh
    ports:
      - 8000:80

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "your-password-here"
    volumes:
      - db:/var/lib/mysql

  client:
    image: elkarbackup/client

volumes:
  db:
  backups:
  uploads:
  sshkeys:
``` 

I thought that  `SYMFONY__DATABASE__PASSWORD:` and ` MYSQL_ROOT_PASSWORD:` should to be different. It was not clear to me that elkarbackup use password from `root` MySQL user to create database. After I've inspected logs I found it. So maybe it's good idea to add more description like `MYSQL_ROOT_PASSWORD` and `SYMFONY__DATABASE__PASSWORD` should to be the same. 

In additional I think we need to add that default username and password for new application is **root/root**. I found it in [documentation](https://docs.elkarbackup.org/docs/installation.html) but it's not clear if you read only description in [docker hub](https://hub.docker.com/r/elkarbackup/elkarbackup/)
